### ISSUE TITLE
0.61.3 Discussion

### ISSUE THREAD

**Issue by grabbou** [react-native-community/releases#150] opened 2019-10-29 10:28 UTC
Conversations on this thread are limited to 0.61 releases major issues and backport (cherry-pick) requests from commits that are already on master.

An example of a good such request is a bug fix for a serious issue that has been merged into master but did not make the 0.61.3 cut.

In other words, if you cannot point to a particular commit on master, then your request likely belongs as a new issue in http://github.com/facebook/react-native/issues.

**Comment by taylorkline** [comment] 2019-10-29 20:07
I may simply be mentioning this too quickly, but the 0.61.3 release notes link to the CHANGELOG for release notes, but there is no 0.61.3 entry in the changelog.

**Comment by LuigiMaestrelli** [comment] 2019-10-29 20:31
A fix that was merged last month and was not released is the hermes on windows machines.
Every build breaks when enabling hermes on Windows.

Here is one of the open [issues](https://github.com/facebook/react-native/issues/25599) about that

**Comment by mikehardy** [comment] 2019-10-29 20:50
@LuigiMaestrelli that looks like a good one! What you want is to put the commit hash in so @grabbou can investigate easily and pick it: https://github.com/facebook/react-native/commit/81a6b6ed3c54498f6f2148c106846352405949bf

And also, thanks @grabbou  :-)

**Comment by tlvenn** [comment] 2019-10-30 00:12
It would be great to include the fix for react-native-gesture-handler which creates quite some friction for the community at the moment.

Issue: https://github.com/kmagiera/react-native-gesture-handler/issues/320#issuecomment-547629967
Fix: https://github.com/facebook/react-native/commit/942de5718236ddbd1a112a2ce7adf20591949672#diff-1eaa4391573b4aa3e399dafeb401f47fR105

I did not check yet personally that is was actually missing in 0.61.3 but according to the latest comment on issue linked above, it appears to be the case.

**Comment by pvinis** [comment] 2019-10-30 09:23
https://github.com/facebook/react-native/pull/27060

**Comment by mjmasn** [comment] 2019-10-30 09:41
After upgrading from 0.61.2 to 0.61.3, our app crashes on startup with `java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libreactnativejni.so caused by: dlopen failed: library "libglog_init.so" not found`.

**Comment by RichardLindhout** [comment] 2019-10-30 12:45
@pvinis Why is react downgraded from 16.9.0 to 16.8.1

**Comment by pvinis** [comment] 2019-10-30 12:47
It was never upgraded. The old cli was somehow getting the right react version, but the new cli is getting the version from the correct file, and that file still has 16.8.1, so I changed that in this PR.

**Comment by RichardLindhout** [comment] 2019-10-30 12:47
Sorry I removed my comment, I did not see your issue number

**Comment by mikehardy** [comment] 2019-10-30 20:43
@tlvenn I am watching https://github.com/kmagiera/react-native-gesture-handler/issues/320#issuecomment-547629967 intently as it causes a crash bug in my app without the workaround. From commentary several of the attentive maintainers are similar watching (cough @kelset cough). I checked the file that is actually in 0.61-stable and the react-native commit is there https://github.com/facebook/react-native/blob/0.61-stable/Libraries/Components/View/ReactNativeViewViewConfig.js#L106 - it has been there for all of 0.61 but for some reason the issue is still happening in the repo.

@grabbou I don't think there's anything to do on the react-native side for https://github.com/facebook/react-native/commit/942de5718236ddbd1a112a2ce7adf20591949672#diff-1eaa4391573b4aa3e399dafeb401f47fR105 - it really is there already

I think the right thing to do is continue conversation on Issue https://github.com/kmagiera/react-native-gesture-handler/issues/320 and Pull https://github.com/kmagiera/react-native-gesture-handler/pull/792

**Comment by tlvenn** [comment] 2019-10-30 20:50
Thanks for the clarification @mikehardy !

**Comment by tlvenn** [comment] 2019-10-30 20:55
Another good candidate probably is the debugging console that is not link log to the source:

Issue: https://github.com/facebook/react-native/issues/26570
Commit: https://github.com/facebook/react-native/commit/42ac240bceb104474494c6007df0089baec00f7a

**Comment by kelset** [comment] 2019-10-31 11:26
FYI the PR @pvinis linked above has been merged: https://github.com/facebook/react-native/pull/27060 🎉

And it's against the 0.61 branch so it will be in for next patch release AFAIK.

re: gesture-handler crash - ditto everything @mikehardy said, it needs a gesture-handler side fix

**Comment by compojoom** [comment] 2019-11-04 09:56
Since 0.61.3 is already out it would be awesome if the fix for react-native-gesture handler makes it into 0.61.4

**Comment by nar213** [comment] 2019-11-04 10:09
Issue: facebook/react-native/issues/26696
Commit: facebook/react-native/pull/27065

Causes crash in background for iOS devices on 2.13 on RN61

**Comment by mikehardy** [comment] 2019-11-04 15:22
@compojoom please read my comment - there is *NO* react-native side change coming for react-native-gesture-handler https://github.com/react-native-community/releases/issues/150#issuecomment-548103862 - something else is going on there, but you're watching the wrong spot if you're looking for a react-native release to fix it. It'll be in the RNGH repo I believe

**Comment by grabbou** [comment] 2019-11-04 16:44
Thank you for the participation in the discussion and @mikehardy for helping me with the moderation! I really appreciate that - sometimes it's just too many things to coordinate!

Let me look into the commits right now - I will proceed with fixes and cherry-picks and hopefully, we can have another release today.

Expect an update from me soon!

**Comment by grabbou** [comment] 2019-11-04 17:11
Thanks @tlvenn and @nar213 for providing both issue and commit. Helps with the process!

**Comment by grabbou** [comment] 2019-11-04 17:19
No more requests for this release. Waiting for the tests and will push to `npm`.

**Closed** 2019-11-04 19:36 UTC
Labels: backport request, stable
