### ISSUE TITLE
0.59.8 Discussion

### ISSUE THREAD

**Issue by grabbou** [react-native-community/releases#124] opened 2019-05-08 13:00 UTC
Conversation on this thread are limited to 0.59.8 release's major issues and cherry-pick requests from commits that are already on master.

An example of a good such request is a bug fix for a serious issue that has been merged into master but did not make the 0.59.7 cut.

In other words, if you cannot point to a particular commit on master, then your request likely belongs as a new issue in http://github.com/facebook/react-native/issues.

If the commit you request to cherry pick is a complicated port, you will be asked to create the PR to the 0.59-stable branch yourself, in order to ensure that the process proceeds smoothly.

**Comment by kelset** [comment] 2019-05-08 14:26
hey @mjmasn nice catch - thanks for pointing it out. I just checked on my "non-trivial" test app (https://github.com/kelset/test-react-nav-with-screens) that updating the patch version of React doesn't create any issues and I couldn't detect any.

But yeah we should modify the changelog to make sure that everyone is aware 👍

**Comment by grabbou** [comment] 2019-05-08 14:57
Thank you the heads up. It was my mistake. Going to publish 0.59.8 again. I forgot to revert the bump commit (which was the reason why 0.59.6 was unpublished).

**Comment by grabbou** [comment] 2019-05-08 17:14
Published as 0.59.8. Didn't cherry-pick https://github.com/react-native-community/releases/issues/124#issuecomment-490476233 because it depends on another commit and it can't be applied easily. 

I also didn't cherry-pick the "Fix accessibility event properties for **TextInput**" ([0a3bbc](https://github.com/facebook/react-native/commit/0a3bbcd1b2c) by [@elucaswork](https://github.com/elucaswork))) because it breaks Detox tests. Waiting for someone to help me debug this.

**Comment by roshangm1** [comment] 2019-05-09 01:16
Was 0.59.7 removed ? I was quick enough to update to 0.57.7 yesterday. :D

**Comment by karanjthakkar** [comment] 2019-05-09 10:32
Can we include this commit: https://github.com/facebook/react-native/commit/c953e0b4319da0976ece877c09b648a55bc57d9f? It fixes a crash while parsing stacktraces in Android.

**Comment by mikehardy** [comment] 2019-05-09 13:48
@karanjthakkar - I double-checked this one since it has bitten me and I thought it was already included, it appears to already be included? https://github.com/facebook/react-native/blob/v0.59.8/ReactAndroid/src/main/java/com/facebook/react/util/JSStackTrace.java#L29

It was included in 0.59.5 actually - https://github.com/facebook/react-native/blob/v0.59.5/ReactAndroid/src/main/java/com/facebook/react/util/JSStackTrace.java#L29

**Comment by karanjthakkar** [comment] 2019-05-09 16:42
@mikehardy I was following this guide to see if that commit made it to a release: https://github.com/react-native-community/releases#when-will-my-fix-make-it-into-a-release And it didnt show up so I thought maybe it isnt released yet.

**Comment by mikehardy** [comment] 2019-05-09 16:45
@karanjthakkar very interesting - yes, there is the .59-stable tag on there, but the other tags (for the point releases) are not there. Not sure if that is a documentation bug vs updated tooling for releases, or whether the releases aren't tagging, or what? I only double-checked because that cherry-pick in particular was the majority of my Android crashes :-). I really wanted to be sure for myself. Cheers

**Comment by kelset** [comment] 2019-05-10 10:33
usually that's caused by cherry-picking, because that basically duplicates the commit so the reference is basically lost, hence why you couldn't see find it.
(anyway, gonna hide the comments)

**Comment by kelset** [comment] 2019-05-15 09:55
If we can, we should try to cherry pick this: https://github.com/facebook/react-native/commit/30348f789946dc99f5ccd02c85c8decbdb9ac29b

it seems that Gradle 3.4.0 causes crashes.

**Comment by jinshin1013** [comment] 2019-05-17 06:10
Can we also cherry pick this if it's not too late?:
- [iOS] Fixes tintColor not changing on Gif image on iOS [facebook/react-native@`75380aa`](https://github.com/facebook/react-native/commit/75380aa3296210777dc0be70a722701767276117)

**Comment by cihati** [comment] 2019-05-24 12:44
@grabbou any news on when this will be released?

**Comment by paolospag** [comment] 2019-05-24 15:22
@grabbou @kelset 
any updates about [this issue](https://github.com/facebook/react-native/issues/24429)?

**Comment by kelset** [comment] 2019-05-27 11:58
👋
given that at the moment there are only, like, 4 commits requested I wanted to wait a bit more before doing a new release. But I feel that I may have some time to tackle this later this week or next week.

**Comment by kelset** [comment] 2019-05-31 08:03
Other commit to cherry pick: https://github.com/facebook/react-native/commit/c87de765f6a9ebf656c188fa2115a1ba01b7939c

**Comment by kelset** [comment] 2019-06-03 14:52
Last commit (likely): https://github.com/facebook/react-native/commit/d8fa1206c3fecd494b0f6abb63c66488e6ced5e0

**Comment by kelset** [comment] 2019-06-05 10:06
Also, if it works, this would be great: https://github.com/facebook/react-native/commit/46c7ada535f8d87f325ccbd96c24993dd522165d

**Comment by kelset** [comment] 2019-06-05 15:29
Hey everyone, I tried to cherry-pick the commits and this is what I ended up with:

* couldn't cherry pick https://github.com/facebook/react-native/commit/20b4879 & https://github.com/facebook/react-native/commit/75380aa3296210777dc0be70a722701767276117 & https://github.com/facebook/react-native/commit/0a3bbcd1b2c (detox fails)

* this was already on branch https://github.com/facebook/react-native/commit/c87de765f6a9ebf656c188fa2115a1ba01b7939c

* you can find the list of the commits cherry picked here: https://github.com/facebook/react-native/commits/0.59-stable

I've done quite some testing and I'm fairly sure that upgrading to this won't require you to do any change in your code (but it will support up to Gradle 5.4.1 & Gradle Tools 3.4.0 & Xcode 11).

I'm waiting now for the last commit I had to cherry pick to go green then I'll do the bump commit.

**Comment by kelset** [comment] 2019-06-05 16:21
Ok, 0.59.9 is out - and upgrading is as simple as changing the version number.

I'll now create the changelog & the release & the tweet & the new issue for next 0.59.x.

**Comment by kelset** [comment] 2019-06-05 16:41
Closing in favour of #127

**Closed by kelset** 2019-06-05 16:41 UTC
Labels: release status, stable
